### ISSUE TITLE
게시글을 읽으면 조회수가 증가한다. 

### ISSUE THREAD

**Issue by miconblog** [miconblog/devcafe#11]
게시글의 조횟수를 노출하는 게시판이 있는 반면 페북처럼 따로 조횟수가 노출되지 않는 게시판도 있다. 
게시판의 성격을 어떻게 규정하느냐에 따라서 조횟수를 인기글의 지표로 볼지 아님 단순한 기록으로 볼지 결정이 필요한다. 
## 인기글을 알고 싶다.

보통 인기글은 조횟수로 알수있는데, 이때 조횟수는 세션상 1회를 가정하고 측정할수있다. 
가령, 어떤 글의 댓글 반응을 지속적으로 모니터하고 싶을때 해당 글을 자꾸 조회하게 되는데 이때 조횟수가 증가하게 되면 자연스럽게 인기글임을 판단할수있다. 
## 게시글을 누가 읽었는지 알고 싶다.

페이스북 처럼 게시글을 누가 읽었는지 알고 싶다면 조횟수가 아닌 이 글을 읽은 사람이 누가 있는지 따로 테이블을 만들어 기록해야한다. 
## 구현방법

읽은확인 테이블
게시글ID - 사용자ID - 읽은시간 
1       -  miconbog - 2012.3.3T12:10:11  

다시 내가 1번글을 읽었을때 현재시간과 비교해서 하루가 안지났으면 그냥 무시,
하루가 지났으면 읽은시간 업데이트해주고, 조회수 1증가!

**Comment by limsungmook** [comment]
고민되던것 두 가지
첫번째, Relation 테이블의 경우 네이밍을 어떻게 할 것인지? 현재는 read_user 라고 자유롭게 명명했는데 다른 의견 있으면 말씀해주세요.

두번째, 이건 현재까지 버전에선 중요치 않은건데요, 매번 글을 읽을 때 마다 마지막 읽은 시간을 가져오기 위해 DB 를 다녀오는 것은 리소스 낭비인 것 같습니다. 나중에 성능이 필요하게 되면 이 부분부터 캐시 도입을 고려해봐야할 듯 합니다.

**Comment by miconblog** [comment]
Redis 캐시에 유효기간 하루짜리로 읽은 포스트 아이디 정보를 삽입하고, 
이 정보가 있으면 조횟수를 증가시키지 않는다!

**Comment by miconblog** [comment]
성능에 문제가 있으면 나중에 다시 고민하는 걸로 일단 이슈 종료!
